package com.ubuntuyouiwe.nexus.presentation.util

enum class RolesCategory(val roleName: String, val roleNameTR: String, val id: String) {
    All("All", "Tümü", "All"),
    NeutralMode("Neutral Mode", "Nötr Mod", "NeutralMode"),
    DebateArena("Debate Arena", "Münazara Meydanı", "DebateArena"),
    Doctor("Doctor", "Doktor", "Doctor"),
    TravelAdvisor("Travel Advisor", "Seyahat Danışmanı", "TravelAdvisor"),
    Chef("Chef", "Şef", "Chef"),
    LiteratureTeacher("Literature Teacher", "Edebiyat Öğretmeni", "LiteratureTeacher"),
    Philosophy("Philosophy", "Felsefe", "Philosophy"),
    SportsPolymath("Sports Polymath", "Spor Polimatı", "SportsPolymath"),
    Lawyer("Lawyer", "Avukat", "Lawyer"),
    RelationshipCoach("Relationship Coach", "İlişki Koçu", "RelationshipCoach"),
    IslamicScholar("Islamic Scholar", "İslam Alimi", "IslamicScholar"),
    Astrologer("Astrologer", "Astrolog", "Astrologer"),
    Bishop("Bishop", "Piskopos", "Bishop"),
    Psychologist("Psychologist", "Psikolog", "Psychologist"),
    PhysicsTeacher("Physics Teacher", "Fizik Öğretmeni", "PhysicsTeacher"),
    ChemistryTeacher("Chemistry Teacher", "Kimya Öğretmeni", "ChemistryTeacher"),
    BiologyTeacher("Biology Teacher", "Biyoloji Öğretmeni", "BiologyTeacher"),
    MathematicsTeacher("Mathematics Teacher", "Matematik Öğretmeni", "MathematicsTeacher"),
    GeographyTeacher("Geography Teacher", "Coğrafya Öğretmeni", "GeographyTeacher"),
    EnglishTeacher("English Teacher", "İngilizce Öğretmeni", "EnglishTeacher"),
    HistoryTeacher("History Teacher", "Tarih Öğretmeni", "HistoryTeacher"),
    Veterinarian("Veterinarian", "Veteriner", "Veterinarian"),
    SoftwareDeveloper("Software Developer", "Yazılım Geliştirici", "SoftwareDeveloper"),
    JustFavorited("Just Favorited", "Favorilenenler", "JustFavorited"),
    JustArchived("Just Archived", "Arşivlenenler", "JustArchived"),
}