package com.ubuntuyouiwe.nexus.presentation.util

enum class RolesCategory(val roleName: String, val  id: String) {
    All("All", "All"),
    NeutralMode("Neutral Mode", "NeutralMode"),
    DebateArena("Debate Arena", "DebateArena"),
    Doctor("Doctor", "Doctor"),
    TravelAdvisor("Travel Advisor", "TravelAdvisor"),
    Chef("Chef", "Chef"),
    LiteratureTeacher("Literature Teacher", "LiteratureTeacher"),
    Philosophy("Philosophy", "Philosophy"),
    SportsPolymath("Sports Polymath", "SportsPolymath"),
    Lawyer("Lawyer", "Lawyer"),
    RelationshipCoach("Relationship Coach", "RelationshipCoach"),
    IslamicScholar("Islamic Scholar", "IslamicScholar"),
    Astrologer("Astrologer", "Astrologer"),
    Bishop("Bishop", "Bishop"),
    Psychologist("Psychologist", "Psychologist"),
    PhysicsTeacher("Physics Teacher", "PhysicsTeacher"),
    ChemistryTeacher("Chemistry Teacher", "ChemistryTeacher"),
    BiologyTeacher("Biology Teacher", "BiologyTeacher"),
    MathematicsTeacher("Mathematics Teacher", "MathematicsTeacher"),
    GeographyTeacher("Geography Teacher", "GeographyTeacher"),
    EnglishTeacher("English Teacher", "EnglishTeacher"),
    HistoryTeacher("History Teacher", "HistoryTeacher"),
    Veterinarian("Veterinarian", "Veterinarian"),
    SoftwareDeveloper("SoftwareDeveloper", "SoftwareDeveloper"),
    JustFavorited("Just Favorited", "JustFavorited"),
    JustArchived("Just Archived", "JustArchived"),

}