package com.ubuntuyouiwe.nexus.domain.model.roles

data class PurposeSelection(
    val isDebateArena: Boolean = false,
    val isTravelAdvisor: Boolean = false,
    val isAstrologer: Boolean = false,
    val isChef: Boolean = false,
    val isSportsPolymath: Boolean = false,
    val isLiteratureTeacher: Boolean = false,
    val isPhilosophy: Boolean = false,
    val isLawyer: Boolean = false,
    val isDoctor: Boolean = false,
    val isIslamicScholar: Boolean = false,
    val isBiologyTeacher: Boolean = false,
    val isChemistryTeacher: Boolean = false,
    val isGeographyTeacher: Boolean = false,
    val isHistoryTeacher: Boolean = false,
    val isMathematicsTeacher: Boolean = false,
    val isPhysicsTeacher: Boolean = false,
    val isPsychologist: Boolean = false,
    val isBishop: Boolean = false,
    val isEnglishTeacher: Boolean = false,
    val isRelationshipCoach: Boolean = false,
    val isVeterinarian: Boolean = false,
    val isSoftwareDeveloper: Boolean = false,
)
